services:
    db:
        image: postgres:15
        container_name: dwltech-postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: adminroot
            POSTGRES_DB: tech_support
        volumes:
            - dwltechdata:/var/lib/postgresql/data

    api:
        build: .
        image: dwltech-backend-img
        container_name: dwltech-backend
        restart: always
        ports:
            - "3333:3333"
        depends_on:
            - db
        volumes:
            - .:/app
            - /app/node_modules
        env_file:
            - .env

    frontend-v2:
        build:
            context: /Users/blackeagle/projetos/renato/dwl/technical_support/frontend-v2
            dockerfile: Dockerfile.dev
        container_name: dwltech-frontend
        ports:
            - "5173:5173"
        volumes:
            - /Users/blackeagle/projetos/renato/dwl/technical_support/frontend-v2:/app
            - /app/node_modules
        environment:
            - VITE_API_URL=http://localhost:3333/api
        depends_on:
            - api

volumes:
    dwltechdata:
